-- Copyright (C) 2018 Open Imaging, Inc.
-- BSD-3

function deviceadapter(name)
   project(name)
      basedir "."
      kind "Bundle"

      links {
         "MMDevice"
      }

      flags {
         "NoImportLib",
      }

      targetprefix "libmmgr_dal_"

      configuration { "windows" }
         targetprefix "mmgr_dal_"

      configuration { "vs*" }
         defines {
            "MODULE_EXPORTS",
         }

   return project()
end


-- A note about device adapter module names:
--
-- The name of a device adapter module is determined by the call(s) to
-- "deviceadapter" in each adapter's GENie script.
--
-- The names listed here are merely the names of the directories containing
-- genie.lua files. As a matter of convension they should usually match the
-- names of the modules, but some included scripts generate more than one
-- module.

-- Sorted ASCII-lexical
include "AAAOTF"
include "ABS"
include "AOTF"
include "ASIFW1000"
include "ASIStage"
include "ASITiger"
include "ASIWPTR"
include "AgilentLaserCombiner"
include "Aladdin"
include "AmScope"
include "Andor"
include "AndorLaserCombiner"
include "AndorSDK3"
include "AndorShamrock"
include "Apogee"
include "Aquinas"
include "Arduino"
include "ArduinoDueFuncGen"
include "BaumerOptronic"
include "BiostepEagleIce"
include "BlueboxOptics_niji"
include "CARVII"
include "CNCMicroscope/ArduinoNeoPixelShutter"
include "CNCMicroscope/RAMPSStage"
include "CSUW1"
include "Cobolt"
include "CoherentCube"
include "CoherentOBIS"
include "CoherentScientificRemote"
include "Conix"
include "CoolLEDpE300"
include "CoolLEDpE4000"
include "Corvus"
include "DTOpenLayer"
include "DemoCamera"
if PROTOC and PROTOBUF_INCLUDE_DIR and PROTOBUF_LIBRARY_DIR then
   include "DirectElectron"
else
   print("Skipping DirectElectron")
end
include "Diskovery"
include "FLICamera"
include "FakeCamera"
include "FreeSerialPort"
include "GenericSLM"
include "GigECamera"
include "HIDManager"
include "HydraLMT200"
include "IDS_uEye"
include "IIDC"
include "ITC18"
include "ImageProcessorChain"
include "Jenoptik"
include "K8055"
include "K8061"
include "LeicaDMI"
include "LeicaDMR"
include "LeicaDMSTC"
include "Ludl"
include "LudlLow"
include "LumencorCIA"
include "LumencorSpectra"
include "MCCDAQ"
include "MCL_MicroDrive"
include "MCL_NanoDrive"
include "MP285"
include "MT20"
include "MaestroServo"
include "Marzhauser"
include "Marzhauser-LStep"
include "MarzhauserLStepOld"
include "MatrixVision"
include "MicroPoint"
include "Mightex"
include "Mightex_BLS"
include "Mightex_C_Cam"
include "Modbus"
include "Motic"
include "MoticMicroscope"
include "NI100X"
include "NIMultiAnalog"
include "Neos"
include "NewportCONEX"
include "NewportSMC"
include "NiMotionStageController"
include "Nikon"
include "NikonTE2000"
include "OVP_ECS2"
include "ObjectiveImaging"
include "Okolab"
include "Omicron"
include "OpenCVgrabber"
include "Oxxius"
include "PCO_Generic"
include "PI"
include "PICAM"
include "PIMotionController"
include "PI_GCS"
include "PI_GCS_2"
include "PVCAM"
include "ParallelPort"
include "PeCon2000"
include "Pecon"
include "PhillipsLEDArray"
include "PicardStage"
include "Piezosystem_30DV50"
include "Piezosystem_NV120_1"
include "Piezosystem_NV40_1"
include "Piezosystem_NV40_3"
include "Piezosystem_dDrive"
include "Piper"
include "PointGrey"
include "PrecisExcite"
include "PrincetonInstruments"
include "Prior"
include "PriorLegacy"
include "QCam"
include "Rapp"
include "RaptorEPIX"
include "Sapphire"
include "Scientifica"
include "ScionCam"
include "ScopeLED"
include "Sensicam"
include "SerialManager"
include "SimpleAutofocus"
include "SmarActHCU-3D"
include "SpectralLMM5"
include "Standa"
include "Standa8SMC4"
include "StandaStage"
include "StanfordPhotonics"
include "SutterLambda"
include "SutterStage"
include "TCPIPPort"
include "TISCam"
include "TSI"
include "TUCam"
include "TeesnySLM"
include "TetheredCam"
include "Thorlabs"
include "ThorlabsAPTStage"
include "ThorlabsDCStage"
include "ThorlabsDCxxxx"
include "ThorlabsFilterWheel"
include "ThorlabsMFC1"
include "ThorlabsSC10"
include "ThorlabsUSBCamera"
include "Tofra"
include "TriggerScope"
include "USBManager"
include "USB_Viper_QPL"
include "UserDefinedSerial"
include "Utilities"
include "VariLC"
include "Vincent"
include "VisiTech_iSIM"
include "Vortran"
include "WieneckeSinske"
include "XCite120PC_Exacte"
include "XCiteLed"
include "XCiteXT600"
include "XLight"
include "Xcite"
include "Ximea"
include "Yokogawa"
include "Zaber"
include "ZeissCAN"
include "ZeissCAN29"
include "dc1394"
include "iPadSLM"
include "kdv"
include "nPoint"
include "pgFocus"
